{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-platform.fullname" . }}-frontend
  labels:
    {{- include "monitoring-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.service.port | default .Values.frontend.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "monitoring-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}

