{{- if .Values.statusPage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-platform.fullname" . }}-status-page
  labels:
    {{- include "monitoring-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: status-page
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.statusPage.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.statusPage.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "monitoring-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: status-page
{{- end }}

