import type { Config } from "tailwindcss";

/*
 * Flight-recorder theme (shared with the documentation website).
 *
 * Every color scale resolves through CSS variables defined at the end of
 * app/globals.css, so the whole app re-skins for dark (default) and light
 * (html[data-theme='light']) without touching component classes:
 *
 *   slate/gray → carbon neutrals      cyan  → international orange (accent)
 *   emerald/green → up               rose/red → down        amber → warn
 *   sky → info azure                 violet → periwinkle    blue → cobalt
 *   indigo → denim                   teal/lime/purple/fuchsia/pink/orange
 *                                    → harmonized categorical ramp
 *
 * 'white' is also variable-backed: it flips to ink in light mode so the
 * ubiquitous text-white / border-white/[α] utilities adapt automatically.
 */
const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "var(--font-sans)",
          "Archivo",
          "ui-sans-serif",
          "-apple-system",
          "Segoe UI",
          "sans-serif",
        ],
        mono: [
          "var(--font-mono)",
          "IBM Plex Mono",
          "SFMono-Regular",
          "Consolas",
          "Menlo",
          "monospace",
        ],
      },
      colors: {
        white: "rgb(var(--tw-white) / <alpha-value>)",
        slate: {
          50: "rgb(var(--tw-slate-50) / <alpha-value>)",
          100: "rgb(var(--tw-slate-100) / <alpha-value>)",
          200: "rgb(var(--tw-slate-200) / <alpha-value>)",
          300: "rgb(var(--tw-slate-300) / <alpha-value>)",
          400: "rgb(var(--tw-slate-400) / <alpha-value>)",
          500: "rgb(var(--tw-slate-500) / <alpha-value>)",
          600: "rgb(var(--tw-slate-600) / <alpha-value>)",
          700: "rgb(var(--tw-slate-700) / <alpha-value>)",
          800: "rgb(var(--tw-slate-800) / <alpha-value>)",
          900: "rgb(var(--tw-slate-900) / <alpha-value>)",
          950: "rgb(var(--tw-slate-950) / <alpha-value>)",
        },
        cyan: {
          50: "rgb(var(--tw-cyan-50) / <alpha-value>)",
          100: "rgb(var(--tw-cyan-100) / <alpha-value>)",
          200: "rgb(var(--tw-cyan-200) / <alpha-value>)",
          300: "rgb(var(--tw-cyan-300) / <alpha-value>)",
          400: "rgb(var(--tw-cyan-400) / <alpha-value>)",
          500: "rgb(var(--tw-cyan-500) / <alpha-value>)",
          600: "rgb(var(--tw-cyan-600) / <alpha-value>)",
          700: "rgb(var(--tw-cyan-700) / <alpha-value>)",
          800: "rgb(var(--tw-cyan-800) / <alpha-value>)",
          900: "rgb(var(--tw-cyan-900) / <alpha-value>)",
          950: "rgb(var(--tw-cyan-950) / <alpha-value>)",
        },
        emerald: {
          50: "rgb(var(--tw-emerald-50) / <alpha-value>)",
          100: "rgb(var(--tw-emerald-100) / <alpha-value>)",
          200: "rgb(var(--tw-emerald-200) / <alpha-value>)",
          300: "rgb(var(--tw-emerald-300) / <alpha-value>)",
          400: "rgb(var(--tw-emerald-400) / <alpha-value>)",
          500: "rgb(var(--tw-emerald-500) / <alpha-value>)",
          600: "rgb(var(--tw-emerald-600) / <alpha-value>)",
          700: "rgb(var(--tw-emerald-700) / <alpha-value>)",
          800: "rgb(var(--tw-emerald-800) / <alpha-value>)",
          900: "rgb(var(--tw-emerald-900) / <alpha-value>)",
          950: "rgb(var(--tw-emerald-950) / <alpha-value>)",
        },
        rose: {
          50: "rgb(var(--tw-rose-50) / <alpha-value>)",
          100: "rgb(var(--tw-rose-100) / <alpha-value>)",
          200: "rgb(var(--tw-rose-200) / <alpha-value>)",
          300: "rgb(var(--tw-rose-300) / <alpha-value>)",
          400: "rgb(var(--tw-rose-400) / <alpha-value>)",
          500: "rgb(var(--tw-rose-500) / <alpha-value>)",
          600: "rgb(var(--tw-rose-600) / <alpha-value>)",
          700: "rgb(var(--tw-rose-700) / <alpha-value>)",
          800: "rgb(var(--tw-rose-800) / <alpha-value>)",
          900: "rgb(var(--tw-rose-900) / <alpha-value>)",
          950: "rgb(var(--tw-rose-950) / <alpha-value>)",
        },
        amber: {
          50: "rgb(var(--tw-amber-50) / <alpha-value>)",
          100: "rgb(var(--tw-amber-100) / <alpha-value>)",
          200: "rgb(var(--tw-amber-200) / <alpha-value>)",
          300: "rgb(var(--tw-amber-300) / <alpha-value>)",
          400: "rgb(var(--tw-amber-400) / <alpha-value>)",
          500: "rgb(var(--tw-amber-500) / <alpha-value>)",
          600: "rgb(var(--tw-amber-600) / <alpha-value>)",
          700: "rgb(var(--tw-amber-700) / <alpha-value>)",
          800: "rgb(var(--tw-amber-800) / <alpha-value>)",
          900: "rgb(var(--tw-amber-900) / <alpha-value>)",
          950: "rgb(var(--tw-amber-950) / <alpha-value>)",
        },
        sky: {
          50: "rgb(var(--tw-sky-50) / <alpha-value>)",
          100: "rgb(var(--tw-sky-100) / <alpha-value>)",
          200: "rgb(var(--tw-sky-200) / <alpha-value>)",
          300: "rgb(var(--tw-sky-300) / <alpha-value>)",
          400: "rgb(var(--tw-sky-400) / <alpha-value>)",
          500: "rgb(var(--tw-sky-500) / <alpha-value>)",
          600: "rgb(var(--tw-sky-600) / <alpha-value>)",
          700: "rgb(var(--tw-sky-700) / <alpha-value>)",
          800: "rgb(var(--tw-sky-800) / <alpha-value>)",
          900: "rgb(var(--tw-sky-900) / <alpha-value>)",
          950: "rgb(var(--tw-sky-950) / <alpha-value>)",
        },
        violet: {
          50: "rgb(var(--tw-violet-50) / <alpha-value>)",
          100: "rgb(var(--tw-violet-100) / <alpha-value>)",
          200: "rgb(var(--tw-violet-200) / <alpha-value>)",
          300: "rgb(var(--tw-violet-300) / <alpha-value>)",
          400: "rgb(var(--tw-violet-400) / <alpha-value>)",
          500: "rgb(var(--tw-violet-500) / <alpha-value>)",
          600: "rgb(var(--tw-violet-600) / <alpha-value>)",
          700: "rgb(var(--tw-violet-700) / <alpha-value>)",
          800: "rgb(var(--tw-violet-800) / <alpha-value>)",
          900: "rgb(var(--tw-violet-900) / <alpha-value>)",
          950: "rgb(var(--tw-violet-950) / <alpha-value>)",
        },
        blue: {
          50: "rgb(var(--tw-blue-50) / <alpha-value>)",
          100: "rgb(var(--tw-blue-100) / <alpha-value>)",
          200: "rgb(var(--tw-blue-200) / <alpha-value>)",
          300: "rgb(var(--tw-blue-300) / <alpha-value>)",
          400: "rgb(var(--tw-blue-400) / <alpha-value>)",
          500: "rgb(var(--tw-blue-500) / <alpha-value>)",
          600: "rgb(var(--tw-blue-600) / <alpha-value>)",
          700: "rgb(var(--tw-blue-700) / <alpha-value>)",
          800: "rgb(var(--tw-blue-800) / <alpha-value>)",
          900: "rgb(var(--tw-blue-900) / <alpha-value>)",
          950: "rgb(var(--tw-blue-950) / <alpha-value>)",
        },
        indigo: {
          50: "rgb(var(--tw-indigo-50) / <alpha-value>)",
          100: "rgb(var(--tw-indigo-100) / <alpha-value>)",
          200: "rgb(var(--tw-indigo-200) / <alpha-value>)",
          300: "rgb(var(--tw-indigo-300) / <alpha-value>)",
          400: "rgb(var(--tw-indigo-400) / <alpha-value>)",
          500: "rgb(var(--tw-indigo-500) / <alpha-value>)",
          600: "rgb(var(--tw-indigo-600) / <alpha-value>)",
          700: "rgb(var(--tw-indigo-700) / <alpha-value>)",
          800: "rgb(var(--tw-indigo-800) / <alpha-value>)",
          900: "rgb(var(--tw-indigo-900) / <alpha-value>)",
          950: "rgb(var(--tw-indigo-950) / <alpha-value>)",
        },
        teal: {
          50: "rgb(var(--tw-teal-50) / <alpha-value>)",
          100: "rgb(var(--tw-teal-100) / <alpha-value>)",
          200: "rgb(var(--tw-teal-200) / <alpha-value>)",
          300: "rgb(var(--tw-teal-300) / <alpha-value>)",
          400: "rgb(var(--tw-teal-400) / <alpha-value>)",
          500: "rgb(var(--tw-teal-500) / <alpha-value>)",
          600: "rgb(var(--tw-teal-600) / <alpha-value>)",
          700: "rgb(var(--tw-teal-700) / <alpha-value>)",
          800: "rgb(var(--tw-teal-800) / <alpha-value>)",
          900: "rgb(var(--tw-teal-900) / <alpha-value>)",
          950: "rgb(var(--tw-teal-950) / <alpha-value>)",
        },
        lime: {
          50: "rgb(var(--tw-lime-50) / <alpha-value>)",
          100: "rgb(var(--tw-lime-100) / <alpha-value>)",
          200: "rgb(var(--tw-lime-200) / <alpha-value>)",
          300: "rgb(var(--tw-lime-300) / <alpha-value>)",
          400: "rgb(var(--tw-lime-400) / <alpha-value>)",
          500: "rgb(var(--tw-lime-500) / <alpha-value>)",
          600: "rgb(var(--tw-lime-600) / <alpha-value>)",
          700: "rgb(var(--tw-lime-700) / <alpha-value>)",
          800: "rgb(var(--tw-lime-800) / <alpha-value>)",
          900: "rgb(var(--tw-lime-900) / <alpha-value>)",
          950: "rgb(var(--tw-lime-950) / <alpha-value>)",
        },
        purple: {
          50: "rgb(var(--tw-purple-50) / <alpha-value>)",
          100: "rgb(var(--tw-purple-100) / <alpha-value>)",
          200: "rgb(var(--tw-purple-200) / <alpha-value>)",
          300: "rgb(var(--tw-purple-300) / <alpha-value>)",
          400: "rgb(var(--tw-purple-400) / <alpha-value>)",
          500: "rgb(var(--tw-purple-500) / <alpha-value>)",
          600: "rgb(var(--tw-purple-600) / <alpha-value>)",
          700: "rgb(var(--tw-purple-700) / <alpha-value>)",
          800: "rgb(var(--tw-purple-800) / <alpha-value>)",
          900: "rgb(var(--tw-purple-900) / <alpha-value>)",
          950: "rgb(var(--tw-purple-950) / <alpha-value>)",
        },
        fuchsia: {
          50: "rgb(var(--tw-fuchsia-50) / <alpha-value>)",
          100: "rgb(var(--tw-fuchsia-100) / <alpha-value>)",
          200: "rgb(var(--tw-fuchsia-200) / <alpha-value>)",
          300: "rgb(var(--tw-fuchsia-300) / <alpha-value>)",
          400: "rgb(var(--tw-fuchsia-400) / <alpha-value>)",
          500: "rgb(var(--tw-fuchsia-500) / <alpha-value>)",
          600: "rgb(var(--tw-fuchsia-600) / <alpha-value>)",
          700: "rgb(var(--tw-fuchsia-700) / <alpha-value>)",
          800: "rgb(var(--tw-fuchsia-800) / <alpha-value>)",
          900: "rgb(var(--tw-fuchsia-900) / <alpha-value>)",
          950: "rgb(var(--tw-fuchsia-950) / <alpha-value>)",
        },
        pink: {
          50: "rgb(var(--tw-pink-50) / <alpha-value>)",
          100: "rgb(var(--tw-pink-100) / <alpha-value>)",
          200: "rgb(var(--tw-pink-200) / <alpha-value>)",
          300: "rgb(var(--tw-pink-300) / <alpha-value>)",
          400: "rgb(var(--tw-pink-400) / <alpha-value>)",
          500: "rgb(var(--tw-pink-500) / <alpha-value>)",
          600: "rgb(var(--tw-pink-600) / <alpha-value>)",
          700: "rgb(var(--tw-pink-700) / <alpha-value>)",
          800: "rgb(var(--tw-pink-800) / <alpha-value>)",
          900: "rgb(var(--tw-pink-900) / <alpha-value>)",
          950: "rgb(var(--tw-pink-950) / <alpha-value>)",
        },
        orange: {
          50: "rgb(var(--tw-orange-50) / <alpha-value>)",
          100: "rgb(var(--tw-orange-100) / <alpha-value>)",
          200: "rgb(var(--tw-orange-200) / <alpha-value>)",
          300: "rgb(var(--tw-orange-300) / <alpha-value>)",
          400: "rgb(var(--tw-orange-400) / <alpha-value>)",
          500: "rgb(var(--tw-orange-500) / <alpha-value>)",
          600: "rgb(var(--tw-orange-600) / <alpha-value>)",
          700: "rgb(var(--tw-orange-700) / <alpha-value>)",
          800: "rgb(var(--tw-orange-800) / <alpha-value>)",
          900: "rgb(var(--tw-orange-900) / <alpha-value>)",
          950: "rgb(var(--tw-orange-950) / <alpha-value>)",
        },
        red: {
          50: "rgb(var(--tw-red-50) / <alpha-value>)",
          100: "rgb(var(--tw-red-100) / <alpha-value>)",
          200: "rgb(var(--tw-red-200) / <alpha-value>)",
          300: "rgb(var(--tw-red-300) / <alpha-value>)",
          400: "rgb(var(--tw-red-400) / <alpha-value>)",
          500: "rgb(var(--tw-red-500) / <alpha-value>)",
          600: "rgb(var(--tw-red-600) / <alpha-value>)",
          700: "rgb(var(--tw-red-700) / <alpha-value>)",
          800: "rgb(var(--tw-red-800) / <alpha-value>)",
          900: "rgb(var(--tw-red-900) / <alpha-value>)",
          950: "rgb(var(--tw-red-950) / <alpha-value>)",
        },
        green: {
          50: "rgb(var(--tw-green-50) / <alpha-value>)",
          100: "rgb(var(--tw-green-100) / <alpha-value>)",
          200: "rgb(var(--tw-green-200) / <alpha-value>)",
          300: "rgb(var(--tw-green-300) / <alpha-value>)",
          400: "rgb(var(--tw-green-400) / <alpha-value>)",
          500: "rgb(var(--tw-green-500) / <alpha-value>)",
          600: "rgb(var(--tw-green-600) / <alpha-value>)",
          700: "rgb(var(--tw-green-700) / <alpha-value>)",
          800: "rgb(var(--tw-green-800) / <alpha-value>)",
          900: "rgb(var(--tw-green-900) / <alpha-value>)",
          950: "rgb(var(--tw-green-950) / <alpha-value>)",
        },
        gray: {
          50: "rgb(var(--tw-gray-50) / <alpha-value>)",
          100: "rgb(var(--tw-gray-100) / <alpha-value>)",
          200: "rgb(var(--tw-gray-200) / <alpha-value>)",
          300: "rgb(var(--tw-gray-300) / <alpha-value>)",
          400: "rgb(var(--tw-gray-400) / <alpha-value>)",
          500: "rgb(var(--tw-gray-500) / <alpha-value>)",
          600: "rgb(var(--tw-gray-600) / <alpha-value>)",
          700: "rgb(var(--tw-gray-700) / <alpha-value>)",
          800: "rgb(var(--tw-gray-800) / <alpha-value>)",
          900: "rgb(var(--tw-gray-900) / <alpha-value>)",
          950: "rgb(var(--tw-gray-950) / <alpha-value>)",
        },
        primary: "#ff5a24",
        success: "rgb(var(--tw-emerald-500) / <alpha-value>)",
        error: "rgb(var(--tw-rose-500) / <alpha-value>)",
        danger: "rgb(var(--tw-rose-500) / <alpha-value>)",
        warning: "rgb(var(--tw-amber-400) / <alpha-value>)",
        muted: "rgb(var(--tw-slate-500) / <alpha-value>)",
      },
      borderRadius: {
        lg: "10px",
        xl: "14px",
        full: "999px",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        subtle: "var(--shadow-subtle)",
      },
    },
  },
  plugins: [],
};
export default config;
